import { StyleSheet } from "react-native";

export const registrationWrapperStyles=StyleSheet.create({
    wrapper:{
        width:"80%",
        height:"70%",
        marginTop:120,
        marginLeft:"auto",
        marginRight:"auto",
        borderRadius:15,
        display:"flex",
        flexDirection:"column",
        alignItems:"center",
        overflow:"hidden"
    },
    header:{
        width:"100%",
        height:60,
        display:"flex",
        flexDirection:"row",
        justifyContent:"center",
        borderBottomColor:"grey",
        borderBottomWidth:1,
        borderStyle:"solid",
    },
    touched:{
        backgroundColor:"rgb(200,200,200)",
        color:"white"
    },
    button:{
       width:"50%",
       height:"100%",
    },
    buttonText:{
        marginTop:18,
        marginLeft:50,
        fontSize:16,
    }
})